/*
 * Album Store API
 *
 * CS6650 Fall 2023
 *
 * API version: 1.0.0
 * Contact: i.gorton@northeasern.edu
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"
	"os"
	"strconv"
	"time"

	"github.com/Shopify/sarama"
	"github.com/gin-gonic/gin"
	"github.com/sony/gobreaker"
)

var kafkaProducer sarama.SyncProducer

func initKafkaProducer(brokers []string) sarama.SyncProducer {
	config := sarama.NewConfig()
	config.Producer.RequiredAcks = sarama.WaitForAll
	config.Producer.Retry.Max = 5
	config.Producer.Return.Successes = true

	producer, err := sarama.NewSyncProducer(brokers, config)
	if err != nil {
		return nil
	}

	return producer
}

func main() {
	kafkaProducer = initKafkaProducer([]string{"localhost:9092"})

	defer func() {
		if err := kafkaProducer.Close(); err != nil {
			log.Printf("Failed to close Kafka producer: %s", err)
		}
	}()

	getBreaker := gobreaker.NewCircuitBreaker(gobreaker.Settings{
		Name:        "kafka-get",
		Timeout:     5 * time.Second,
		ReadyToTrip: func(counts gobreaker.Counts) bool { return counts.ConsecutiveFailures > 3 },
	})

	postBreaker := gobreaker.NewCircuitBreaker(gobreaker.Settings{
		Name:        "kafka-post",
		Timeout:     5 * time.Second,
		ReadyToTrip: func(counts gobreaker.Counts) bool { return counts.ConsecutiveFailures > 3 },
	})

	// Setup Gin engine
	r := gin.Default()

	r.GET("/album/:albumId", func(c *gin.Context) {
		albumId := c.Param("albumId")
		id, err := strconv.Atoi(albumId)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid album value"})
		}

		getMsg := &sarama.ProducerMessage{
			Topic: "album-get",
			Key:   sarama.StringEncoder(albumId),
			Value: sarama.StringEncoder("GET request for album " + albumId),
		}

		_, err = getBreaker.Execute(func() (interface{}, error) {
			_, _, err := kafkaProducer.SendMessage(getMsg)
			return nil, err
		})

		if err != nil {
			log.Printf("Failed to send message to Kafka: %s", err)
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to get album"})
			return
		}

		// Create a Kafka consumer to wait for a response (synchronous polling)
		consumer, err := sarama.NewConsumer([]string{"localhost:9092"}, nil)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to create Kafka consumer"})
			return
		}
		defer consumer.Close()

		partitionConsumer, err := consumer.ConsumePartition("album-response", 0, sarama.OffsetNewest)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to consume Kafka response"})
			return
		}
		defer partitionConsumer.Close()

		select {
		case msg := <-partitionConsumer.Messages():
			// Assume msg.Value holds the data we want
			c.JSON(http.StatusOK, gin.H{"message": "Album retrieved", "albumId": albumId, "data": string(msg.Value)})
		case <-time.After(5 * time.Second):
			c.JSON(http.StatusGatewayTimeout, gin.H{"error": "Timeout waiting for album data"})
		}

		c.JSON(http.StatusOK, gin.H{"message": "Album retrieved", "albumId": id})
	})

	// POST /insert -> inserts a row with some random value
	r.POST("/album", func(c *gin.Context) {
		profileStr := c.PostForm("profile")
		if profileStr == "" {
			c.JSON(http.StatusBadRequest, gin.H{"error": "Missing profile field"})
			return
		}

		postMsg := &sarama.ProducerMessage{
			Topic: "album-post",
			Key:   sarama.StringEncoder("album-key"),
			Value: sarama.StringEncoder("POST request for album " + profileStr),
		}

		_, err := postBreaker.Execute(func() (interface{}, error) {
			_, _, err := kafkaProducer.SendMessage(postMsg)
			return nil, err
		})

		if err != nil {
			log.Printf("Failed to send message to Kafka: %s", err)
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to create album"})
			return
		}

		c.JSON(http.StatusOK, gin.H{"message": "Album created", "albumId": 1, "imageSize": 100})
	})

	// Optionally, pass a port via environment variable or default to 8080
	port := os.Getenv("PORT")
	if port == "" {
		port = "8082"
	}

	log.Printf("Server starting on port %s ...", port)
	r.Run(":" + port)
}
